### ISSUE TITLE
Использовать уже реализованный fetch-модуль.

### ISSUE THREAD

**Issue by azinit** [martis-git/rezak-summarizator#19]
https://github.com/martis-git/rezak-summarizator/blob/efb4a3325127c8625fbd81740fc4502659ebed28/client/chrome/scripts/fetch.ts

Либо же вынести существующий на уровень выше

**Comment by niyazm524** [comment]
Я прям надеялся что ты подправишь потом эту копипасту)

**Comment by azinit** [comment]
@niyazm524 
Ну вот и отметил себе - чтобы не забыть)
